// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GetMember struct {
	ID        string `json:"_id"`
	Nickname  string `json:"nickname"`
	Color     string `json:"color"`
	Image     string `json:"image"`
	CreatedAt string `json:"createdAt"`
}

type GetMessage struct {
	ID          string                     `json:"_id"`
	Member      *GetMember                 `json:"member"`
	Content     string                     `json:"content"`
	CreatedAt   string                     `json:"createdAt"`
	Emoji       []*GetMessageReactionEmoji `json:"emoji"`
	ChannelName string                     `json:"channelName"`
}

type GetMessageReactionEmoji struct {
	MemberID  []*string `json:"memberID"`
	EmojiCode string    `json:"emojiCode"`
}

type Member struct {
	ID        string `json:"_id"`
	Nickname  string `json:"nickname"`
	Color     string `json:"color"`
	Image     string `json:"image"`
	CreatedAt string `json:"createdAt"`
}

type Message struct {
	ID          string                  `json:"_id"`
	Member      *Member                 `json:"member"`
	Content     string                  `json:"content"`
	CreatedAt   string                  `json:"createdAt"`
	Emoji       []*MessageReactionEmoji `json:"emoji"`
	ChannelName string                  `json:"channelName"`
}

type MessageReactionEmoji struct {
	MemberID  []*string `json:"memberID"`
	EmojiCode string    `json:"emojiCode"`
}
